//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnroidApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostAward
    {
        public int Id { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public Nullable<int> AnswerId { get; set; }
        public string FillAnswer { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Anwser Anwser { get; set; }
        public virtual Question Question { get; set; }
    }
}
